OUTDIR := "../out"
TSRCS := "../src/display.c ../src/rtc.c ../src/button.c ../src/mode.c ./stubbed/testindex.c"

TCFLAGS := f"-g -std=gnu99 -DSTUBBED=1 -I../src -I./stubbed/ -Wall -Wno-unused-variable {{TSRCS}}"

main:
  gcc {{TCFLAGS}} ../src/main.c -o {{OUTDIR}}/test_main
  {{OUTDIR}}/test_main

button: (test "button")

mode: (test "mode")

test source:
  gcc {{TCFLAGS}} ./{{source}}_test.c -o {{OUTDIR}}/test_{{source}}
  {{OUTDIR}}/test_{{source}}
